package com.wsm.model;
// Generated May 21, 2016 9:39:06 PM by Hibernate Tools 5.1.0.Alpha1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Building generated by hbm2java
 */
@Entity
@Table(name = "building", catalog = "watermeter")
public class Building implements java.io.Serializable {

	private Integer oid;
	private District district;
	private Integer age;
	private BigDecimal buildingSize;
	private String address;
	private Set<SmartMeter> smartMeters = new HashSet<SmartMeter>(0);
	private Set<Household> households = new HashSet<Household>(0);

	public Building() {
	}

	public Building(District district, Integer age, BigDecimal buildingSize, String address,
			Set<SmartMeter> smartMeters, Set<Household> households) {
		this.district = district;
		this.age = age;
		this.buildingSize = buildingSize;
		this.address = address;
		this.smartMeters = smartMeters;
		this.households = households;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "oid", unique = true, nullable = false)
	public Integer getOid() {
		return this.oid;
	}

	public void setOid(Integer oid) {
		this.oid = oid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "district_oid")
	public District getDistrict() {
		return this.district;
	}

	public void setDistrict(District district) {
		this.district = district;
	}

	@Column(name = "age")
	public Integer getAge() {
		return this.age;
	}

	public void setAge(Integer age) {
		this.age = age;
	}

	@Column(name = "building_size")
	public BigDecimal getBuildingSize() {
		return this.buildingSize;
	}

	public void setBuildingSize(BigDecimal buildingSize) {
		this.buildingSize = buildingSize;
	}

	@Column(name = "address")
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "building")
	public Set<SmartMeter> getSmartMeters() {
		return this.smartMeters;
	}

	public void setSmartMeters(Set<SmartMeter> smartMeters) {
		this.smartMeters = smartMeters;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "building")
	public Set<Household> getHouseholds() {
		return this.households;
	}

	public void setHouseholds(Set<Household> households) {
		this.households = households;
	}

}
