package com.wsm.model;
// Generated May 21, 2016 9:39:06 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ComplexDeviceInstance generated by hbm2java
 */
@Entity
@Table(name = "complex_device_instance", catalog = "watermeter")
public class ComplexDeviceInstance implements java.io.Serializable {

	private int oid;
	private DeviceType deviceType;
	private Household household;
	private String efficiency;
	private Boolean ecomode;
	private Boolean timer;
	private Set<DeviceConsumption> deviceConsumptions = new HashSet<DeviceConsumption>(0);

	public ComplexDeviceInstance() {
	}

	public ComplexDeviceInstance(int oid) {
		this.oid = oid;
	}

	public ComplexDeviceInstance(int oid, DeviceType deviceType, Household household, String efficiency,
			Boolean ecomode, Boolean timer, Set<DeviceConsumption> deviceConsumptions) {
		this.oid = oid;
		this.deviceType = deviceType;
		this.household = household;
		this.efficiency = efficiency;
		this.ecomode = ecomode;
		this.timer = timer;
		this.deviceConsumptions = deviceConsumptions;
	}

	@Id

	@Column(name = "oid", unique = true, nullable = false)
	public int getOid() {
		return this.oid;
	}

	public void setOid(int oid) {
		this.oid = oid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "device_type_oid")
	public DeviceType getDeviceType() {
		return this.deviceType;
	}

	public void setDeviceType(DeviceType deviceType) {
		this.deviceType = deviceType;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "household_oid")
	public Household getHousehold() {
		return this.household;
	}

	public void setHousehold(Household household) {
		this.household = household;
	}

	@Column(name = "efficiency")
	public String getEfficiency() {
		return this.efficiency;
	}

	public void setEfficiency(String efficiency) {
		this.efficiency = efficiency;
	}

	@Column(name = "ecomode")
	public Boolean getEcomode() {
		return this.ecomode;
	}

	public void setEcomode(Boolean ecomode) {
		this.ecomode = ecomode;
	}

	@Column(name = "timer")
	public Boolean getTimer() {
		return this.timer;
	}

	public void setTimer(Boolean timer) {
		this.timer = timer;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "complexDeviceInstance")
	public Set<DeviceConsumption> getDeviceConsumptions() {
		return this.deviceConsumptions;
	}

	public void setDeviceConsumptions(Set<DeviceConsumption> deviceConsumptions) {
		this.deviceConsumptions = deviceConsumptions;
	}

}
