package com.wsm.model;
// Generated May 21, 2016 9:39:06 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DeviceType generated by hbm2java
 */
@Entity
@Table(name = "device_type", catalog = "watermeter")
public class DeviceType implements java.io.Serializable {

	private int oid;
	private String name;
	private String icon;
	private String type;
	private Set<ComplexDeviceInstance> complexDeviceInstances = new HashSet<ComplexDeviceInstance>(0);

	public DeviceType() {
	}

	public DeviceType(int oid) {
		this.oid = oid;
	}

	public DeviceType(int oid, String name, String icon, String type,
			Set<ComplexDeviceInstance> complexDeviceInstances) {
		this.oid = oid;
		this.name = name;
		this.icon = icon;
		this.type = type;
		this.complexDeviceInstances = complexDeviceInstances;
	}

	@Id

	@Column(name = "oid", unique = true, nullable = false)
	public int getOid() {
		return this.oid;
	}

	public void setOid(int oid) {
		this.oid = oid;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "icon", length = 65535)
	public String getIcon() {
		return this.icon;
	}

	public void setIcon(String icon) {
		this.icon = icon;
	}

	@Column(name = "type")
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "deviceType")
	public Set<ComplexDeviceInstance> getComplexDeviceInstances() {
		return this.complexDeviceInstances;
	}

	public void setComplexDeviceInstances(Set<ComplexDeviceInstance> complexDeviceInstances) {
		this.complexDeviceInstances = complexDeviceInstances;
	}

}
