package com.wsm.model;
// Generated May 21, 2016 9:39:06 PM by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Module generated by hbm2java
 */
@Entity
@Table(name = "module", catalog = "watermeter")
public class Module implements java.io.Serializable {

	private int oid;
	private String moduleid;
	private String moduledomainname;

	public Module() {
	}

	public Module(int oid) {
		this.oid = oid;
	}

	public Module(int oid, String moduleid, String moduledomainname) {
		this.oid = oid;
		this.moduleid = moduleid;
		this.moduledomainname = moduledomainname;
	}

	@Id

	@Column(name = "oid", unique = true, nullable = false)
	public int getOid() {
		return this.oid;
	}

	public void setOid(int oid) {
		this.oid = oid;
	}

	@Column(name = "moduleid")
	public String getModuleid() {
		return this.moduleid;
	}

	public void setModuleid(String moduleid) {
		this.moduleid = moduleid;
	}

	@Column(name = "moduledomainname")
	public String getModuledomainname() {
		return this.moduledomainname;
	}

	public void setModuledomainname(String moduledomainname) {
		this.moduledomainname = moduledomainname;
	}

}
