package com.wsm.model;
// Generated May 21, 2016 9:39:06 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * SimpleDeviceInstance generated by hbm2java
 */
@Entity
@Table(name = "simple_device_instance", catalog = "watermeter")
public class SimpleDeviceInstance implements java.io.Serializable {

	private int oid;
	private Integer number;
	private Integer deviceTypeOid;
	private Integer householdOid;
	private Set<DeviceConsumption> deviceConsumptions = new HashSet<DeviceConsumption>(0);

	public SimpleDeviceInstance() {
	}

	public SimpleDeviceInstance(int oid) {
		this.oid = oid;
	}

	public SimpleDeviceInstance(int oid, Integer number, Integer deviceTypeOid, Integer householdOid,
			Set<DeviceConsumption> deviceConsumptions) {
		this.oid = oid;
		this.number = number;
		this.deviceTypeOid = deviceTypeOid;
		this.householdOid = householdOid;
		this.deviceConsumptions = deviceConsumptions;
	}

	@Id

	@Column(name = "oid", unique = true, nullable = false)
	public int getOid() {
		return this.oid;
	}

	public void setOid(int oid) {
		this.oid = oid;
	}

	@Column(name = "number")
	public Integer getNumber() {
		return this.number;
	}

	public void setNumber(Integer number) {
		this.number = number;
	}

	@Column(name = "device_type_oid")
	public Integer getDeviceTypeOid() {
		return this.deviceTypeOid;
	}

	public void setDeviceTypeOid(Integer deviceTypeOid) {
		this.deviceTypeOid = deviceTypeOid;
	}

	@Column(name = "household_oid")
	public Integer getHouseholdOid() {
		return this.householdOid;
	}

	public void setHouseholdOid(Integer householdOid) {
		this.householdOid = householdOid;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "simpleDeviceInstance")
	public Set<DeviceConsumption> getDeviceConsumptions() {
		return this.deviceConsumptions;
	}

	public void setDeviceConsumptions(Set<DeviceConsumption> deviceConsumptions) {
		this.deviceConsumptions = deviceConsumptions;
	}

}
