package com.wsm.model;
// Generated May 21, 2016 9:39:06 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * SmartMeter generated by hbm2java
 */
@Entity
@Table(name = "smart_meter", catalog = "watermeter")
public class SmartMeter implements java.io.Serializable {

	private Integer oid;
	private Building building;
	private String smartMeterId;
	private Set<MeterReading> meterReadings = new HashSet<MeterReading>(0);
	private Set<Household> households = new HashSet<Household>(0);

	public SmartMeter() {
	}

	public SmartMeter(Building building, String smartMeterId, Set<MeterReading> meterReadings,
			Set<Household> households) {
		this.building = building;
		this.smartMeterId = smartMeterId;
		this.meterReadings = meterReadings;
		this.households = households;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "oid", unique = true, nullable = false)
	public Integer getOid() {
		return this.oid;
	}

	public void setOid(Integer oid) {
		this.oid = oid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "building_oid")
	public Building getBuilding() {
		return this.building;
	}

	public void setBuilding(Building building) {
		this.building = building;
	}

	@Column(name = "smart_meter_id")
	public String getSmartMeterId() {
		return this.smartMeterId;
	}

	public void setSmartMeterId(String smartMeterId) {
		this.smartMeterId = smartMeterId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "smartMeter")
	public Set<MeterReading> getMeterReadings() {
		return this.meterReadings;
	}

	public void setMeterReadings(Set<MeterReading> meterReadings) {
		this.meterReadings = meterReadings;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "smartMeter")
	public Set<Household> getHouseholds() {
		return this.households;
	}

	public void setHouseholds(Set<Household> households) {
		this.households = households;
	}

}
