package com.wsm.model;
// Generated May 21, 2016 9:39:06 PM by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user", catalog = "watermeter")
public class User implements java.io.Serializable {

	private int oid;
	private String username;
	private String password;
	private String email;
	private String firstName;
	private String lastName;
	private String birthDate;
	private Boolean internal;
	private NeutralUser neutralUser;

	public User() {
	}

	public User(int oid) {
		this.oid = oid;
	}

	public User(int oid, String username, String password, String email, String firstName, String lastName,
			String birthDate, Boolean internal, NeutralUser neutralUser) {
		this.oid = oid;
		this.username = username;
		this.password = password;
		this.email = email;
		this.firstName = firstName;
		this.lastName = lastName;
		this.birthDate = birthDate;
		this.internal = internal;
		this.neutralUser = neutralUser;
	}

	@Id

	@Column(name = "oid", unique = true, nullable = false)
	public int getOid() {
		return this.oid;
	}

	public void setOid(int oid) {
		this.oid = oid;
	}

	@Column(name = "username")
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "password")
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "email")
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "first_name")
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "last_name")
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "birth_date")
	public String getBirthDate() {
		return this.birthDate;
	}

	public void setBirthDate(String birthDate) {
		this.birthDate = birthDate;
	}

	@Column(name = "internal")
	public Boolean getInternal() {
		return this.internal;
	}

	public void setInternal(Boolean internal) {
		this.internal = internal;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "user")
	public NeutralUser getNeutralUser() {
		return this.neutralUser;
	}

	public void setNeutralUser(NeutralUser neutralUser) {
		this.neutralUser = neutralUser;
	}

}
